### ISSUE TITLE
Conflict: terminated by other long poll or webhook

### ISSUE THREAD

**Issue by ezar** [MMRIZE/MMM-TelegramBot#13]
Every second I get this error:

error_code: 409,
0|MagicMir |         description: 'Conflict: terminated by other long poll or webhook'

**Comment by eouia** [comment]
I think it is related to a port using. TelegramBot module was trying to use some port for webhook, but There might be another program which was using already or trying.
Try changing your MM port number. (If your mirror has another module to use polling or web hooking, it could make interference also.)

**Comment by ezar** [comment]
Nothing. Same problem!

**Comment by eouia** [comment]
When you’ve got the problem? From first time after installation? Or after some days on success?
Have you tried to run only this module without any others(except default modules)? 
And have you anything specially running except MM on your RPI?(like some background music player, home automation, or retropi...)

**Comment by ezar** [comment]
I find the error. I reinstall everything!
