### ISSUE TITLE
Too many instances when MM is in server mode

### ISSUE THREAD

**Issue by ezar** [MMRIZE/MMM-TelegramBot#16]
I open a remote browser to MM and telegram bot fails making MM hangs.
Why I can open two remote connections?
You can try error if open MM web from other computer browser.

**Comment by eouia** [comment]
Sorry for absence. I was stuck on my real job. sorry again.
MMM-TelegramBot doesn't support multi instances, because it is very difficult to distinguish each instance. So, execution multiple could cause errors. I didn't consider multi instances at first.
