### ISSUE TITLE
message more times

### ISSUE THREAD

**Issue by fischi87** [MMRIZE/MMM-TelegramBot#18]
Hello, when i write for example /help in my bot i get a answer but more then one time. sometimes 2 same answers somtimes 4 answers. whats happened there?

**Comment by eouia** [comment]
You might run MM instance twice or several times.
Have you run your MM by `pm2`? or `npm start` for testing?

**Comment by fischi87** [comment]
ah okay, after reboot it works. i had open 2 instance, sorry my fault

**Comment by eouia** [comment]
nice to you. I'll close this issue.
