### ISSUE TITLE
Where to add custom commands?

### ISSUE THREAD

**Issue by mungle** [MMRIZE/MMM-TelegramBot#19]
Hello!
I red the wiki but I'm unable to understand where I can add a simple notification.
I want to use telegram to select next pages with this module: https://github.com/edward-shen/MMM-pages

Thank you

**Comment by eouia** [comment]
Can you modify the code by yourself? Or you should request the module creator to support this.
If you want to modify it by yourself, I can help you.

**Comment by eouia** [comment]
Can you modify the code by yourself? Or you should request the module creator to support this.
If you want to modify it by yourself, I can help you.

**Comment by mungle** [comment]
Yes, I can

**Comment by eouia** [comment]
Insert belows in `MMM-pages.js`. I think line 18 is good place to insert.
```
getCommands: function(commander) {
  return [
    {command: 'PAGE_CHANGED'},
    {command: 'PAGE_INCREMENT'},
    {command: 'PAGE_DECREMENT'},
  ]
},
```

Now you can get commands 
- `/PAGE_CHANGED number`
- `/PAGE_INCREMENT`
- `/PAGE_DECREMENT`

**Comment by eouia** [comment]
More detailed information is here;
https://github.com/eouia/MMM-TelegramBot/wiki/How-to-add-commands

**Comment by eouia** [comment]
Have you solved your problem? I'll close this.
