### ISSUE TITLE
Not allowed to command bot, ask Admin

### ISSUE THREAD

**Issue by Kevsw99** [MMRIZE/MMM-TelegramBot#20]
Hi, i always do get this message from my bot, can you help me out with this?

magicMirrorBot, [01.11.18 11:37]
[In reply to Kevin W]
You are not allowed to command me. Ask admin.

**Comment by eouia** [comment]
I think you'd missed `allowedUser` in configuration. For security reason, only allowed user can command to TelegramBot in your chat room.
If you want to give a permission to multi users, set like this;
```
allowedUser: ["tom1234", "jake_work", ...],
```

**Comment by Kevsw99** [comment]
i did add my tele username before though
{
  module: 'MMM-TelegramBot',
  config: {
    telegramAPIKey : '<your Telegram API Token>',
    allowedUser : 'KevinW99', // This is NOT the username of bot.
  }
},

**Comment by eouia** [comment]
allowedUser is `Array of string`, so, it should be in array `[  ]` 
```
allowedUser: ["KevinW99"],
```

**Comment by Kevsw99** [comment]
Ah alright, ill try it our tomorrow and get back to you if it does work

**Comment by Kevsw99** [comment]
{
module: 'MMM-TelegramBot',
config: {
telegramAPIKey : 'gytdyuccyuibcxtfyguhjcd', // this is just a sample api key
allowedUser : ['KevinW99'], 
}
},
![unnamed](https://user-images.githubusercontent.com/43768843/47889960-8221bb00-de87-11e8-8a37-9fba7c0a1c74.jpg)

Currently this is my code, is there anything wrong with this?

**Comment by Kevsw99** [comment]
I tried making  new bot and still does not work though

**Comment by eouia** [comment]
First, Check your telegram API Key. It would look like "556021590:XAGPwvet2CdybsmXyJnQN_eflnRsnDVz-ZX".
Second, 
Check your serverside log (`show pm2 log` or result of `npm start dev`), Is there any error?

If you ask something (e.g: `/something`) on Telegram, 
The serverlogs will be something like this;`[TELBOT][2018-11-02 08:19:59]Message is coming from CHAT:41286649`
If there is no error log but still doesn't work, tell me. I'll send a file of modified version to check points.

**Comment by Kevsw99** [comment]
alrite, ill check it on tuesday whhen i get back to my intern desk, and yeah the api key is just hidden for security reasons.

**Comment by Kevsw99** [comment]
I am so sorry for the late reply but i can only resume this project on 12 November so only then i can test and let you know whether it does work or not.

**Comment by Kevsw99** [comment]
Hi, i have checked it again and there is no error log whatsoever, so i am not to sure what to do now.

**Comment by eouia** [comment]
Can I test your telegram API Key and username? (just for a check. you can re-get those)
My email is eouia0819@gmail.com

**Comment by michael5r** [comment]
@Kevsw99 Aren't you missing the `adminChatId` from your config?

**Comment by michael5r** [comment]
You need all three settings:
```js
config: {
    telegramAPIKey: '<your-api-key>',
    allowedUser: ['<your-allowed-user>'],
    adminChatId: '<your-admin-chat-id>'
}
```

**Comment by eouia** [comment]
@michael5r Good point, but I think he had some problem to get `adminChatId` even in first execution. `/mychatid` or `help` should work even without `adminChatId`.
Anyway, I'll close this issue because it's too old. If @Kevsw99 has still a problem, reopen it. Thanks.
