### ISSUE TITLE
Restarted on message appears randomly.

### ISSUE THREAD

**Issue by radokristof** [MMRIZE/MMM-TelegramBot#23]
Hi!

The 'restarted on...' message appears randomly, even when MagicMirror is not restarted.
Why it happens?

Alternatively, can I turn this message off?

**Comment by eouia** [comment]
Hmmm.. that message will be bursted on start of module. Have you refreshed it?
Or tell me which environment are you using.

**Comment by radokristof** [comment]
I’m not even at home where the Mirror is. Haven’t touched anything. RPi 3B

**Comment by eouia** [comment]
if your are using `pm2` and your mirror or RPI has some trouble to maintain MM, MM will restart automatically. In that case, the message will be bursted again (Ant that is the purpose of the message)
Or, you are using multi-thread PC as Mirror hosting computer, it could happen. that case?

**Comment by radokristof** [comment]
Yes I'm using with pm2. If I use a service for that instead pm2 that could solve this restart issue?

**Comment by eouia** [comment]
No, it means your MM is not stable so it restarts often. You should check your system and modules to figure why your mm restarts so repeatedly.
Anyway I’ll patch for option to use or not welcomeMsg in a few days(after my kids vacation)

**Comment by ghost** [comment]
Is it possible the welcome message on the reboot of MM? I'll reboot my mirror couple of times per week (not running when not at home etc.) and I do not really need a welcome message every time. Mirror works fine..

**Comment by eouia** [comment]
@FatTony123 @radokristof 
I'll add a feature of turning-off bootup message by configuration on next updates

**Comment by eouia** [comment]
Updated. Please test it.

**Comment by ghost** [comment]
@eouia works fine, just tested! Thanks!
