### ISSUE TITLE
/reboot and /shutdown are for RPI and not MM ? 

### ISSUE THREAD

**Issue by azro352** [MMRIZE/MMM-TelegramBot#24]
When using `/commands` we get

    /reboot - Reboot MagicMirror
    /shutdown- Shutdown MagicMirror

But it is the rasperry instead of the MagicMirror app, isn't it ?

**Comment by eouia** [comment]
Yes. not for MM itself. If you need, you can make one by yourself.

**Comment by azro352** [comment]
I just noted it, maybe to update the message related to these commands ;)
