### ISSUE TITLE
Allow user by phone number instead of username

### ISSUE THREAD

**Issue by 29axe** [MMRIZE/MMM-TelegramBot#30]
Hi, 
I don't have any username set for my telegram account and I'm not really willing to do it. 
I tried adding my phone number in the list of allowed users instead but it's not working. The bot says : not allowed to use commands, ask admin.
Is there as way to make it work using a phone number?

**Comment by eouia** [comment]
Sorry, no. username is only and unique identifier of an account to handle.  username couldn't be derived from phone number. About the safety issue, I think phone number is more important than username. 
If worried, how about making a new account only for this?
