### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by Yuhan-1in** [MMRIZE/MMM-TelegramBot#31]
I got these messages after npm install

npm WARN MMM-TelegramBot@1.0.2 No repository field.
npm WARN MMM-TelegramBot@1.0.2 No license field.

Also, my bot has no response

**Comment by eouia** [comment]
Those messages are just warning not issue. It is not the reason of your problem.
Show me your configuration and backend log.

**Comment by Yuhan-1in** [comment]
I used the HTTP way to get my chat_id and it's working now
