### ISSUE TITLE
telegram ip is not available

### ISSUE THREAD

**Issue by vitos1k** [MMRIZE/MMM-TelegramBot#32]
is there a way to alter telegram ip address?
in my country some of the direct telegram ip's are blocked, but bot still tries to connect 
>  RequestError: Error: connect ETIMEDOUT 149.154.167.220:443

**Comment by eouia** [comment]
have no idea about alt ip. sorry...

**Comment by Barokai** [comment]
somebody could try his luck with all "known" telegram ip adresses: https://db-ip.com/as62041
:)

**Comment by eouia** [comment]
To know exactly what happens. Which country are you living? Russia?
And full error log be needed.

**Comment by eouia** [comment]
I have been reading some discussion about this issue; most of ppl recommend to use VPN to avoid this. (in Russia and China)

**Comment by vitos1k** [comment]
yes i'm from russia. I can find alternate telegram ip. I just need to know how to change it in the code of TelegramBot. Or if there is a parameter to use specific IP address?

`/home/pi/.pm2/logs/mm-out.log last 15 lines:
0|mm       | [15:01:31.957] [LOG]    Module helper loaded: newsfeed
0|mm       | [15:01:31.959] [LOG]    All module helpers loaded.
0|mm       | [15:01:31.961] [LOG]    Starting server on port 8080 ...
0|mm       | [15:01:31.988] [LOG]    Server started ...
0|mm       | [15:01:31.990] [LOG]    Connecting socket for: updatenotification
0|mm       | [15:01:31.992] [LOG]    Connecting socket for: calendar
0|mm       | [15:01:31.993] [LOG]    Starting node helper for: calendar
0|mm       | [15:01:31.995] [LOG]    Connecting socket for: MMM-TelegramBot
0|mm       | [15:01:31.998] [LOG]    Connecting socket for: MMM-Tools
0|mm       | [15:01:32.002] [LOG]    Connecting socket for: newsfeed
0|mm       | [15:01:32.004] [LOG]    Starting module: newsfeed
0|mm       | [15:01:32.005] [LOG]    Sockets connected & modules started ...
0|mm       | [15:01:33.560] [LOG]    Launching application.
0|mm       | [15:01:38.434] [LOG]    Create new calendar fetcher for url: https:                                                                                                                                                             //yalov.github.io/files/iCalendar/ical-rus-out.ics - Interval: 300000
0|mm       | [15:01:38.924] [LOG]    Create new news fetcher for url: https://ne                                                                                                                                                             ws.yandex.ru/cosmos.rss - Interval: 300000

0|mm  | [15:02:11.520] [ERROR]
0|mm  | { RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
0|mm  |     at new RequestError (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/errors.js:14:15)
0|mm  |     at Request.plumbing.callback (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/plumbing.js:87:29)
0|mm  |     at Request.RP$callback [as _callback] (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/plumbing.js:46:31)
0|mm  |     at self.callback (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request/request.js:185:22)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request/request.js:877:8)
0|mm  |     at ClientRequest.emit (events.js:182:13)
0|mm  |     at TLSSocket.socketErrorListener (_http_client.js:382:9)
0|mm  |     at TLSSocket.emit (events.js:182:13)
0|mm  |     at emitErrorNT (internal/streams/destroy.js:82:8)
0|mm  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
0|mm  |     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'EFATAL' }
0|mm  | [15:02:11.570] [WARN]
0|mm  | Unhandled rejection RequestError: Error: connect ETIMEDOUT 149.154.167.220:443
0|mm  |     at new RequestError (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/errors.js:14:15)
0|mm  |     at Request.plumbing.callback (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/plumbing.js:87:29)
0|mm  |     at Request.RP$callback [as _callback] (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request-promise-core/lib/plumbing.js:46:31)
0|mm  |     at self.callback (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request/request.js:185:22)
0|mm  |     at Request.emit (events.js:182:13)
0|mm  |     at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-TelegramBot/node_modules/request/request.js:877:8)
0|mm  |     at ClientRequest.emit (events.js:182:13)
0|mm  |     at TLSSocket.socketErrorListener (_http_client.js:382:9)
0|mm  |     at TLSSocket.emit (events.js:182:13)
0|mm  |     at emitErrorNT (internal/streams/destroy.js:82:8)
0|mm  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
0|mm  |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|mm  | [15:02:21.723] [LOG]
0|mm  | [TELBOT] Error: EFATAL
`

**Comment by vitos1k** [comment]
oh my bad. I now understand, that it's more of  iptables problem, than yours. there is no direct ip manipulation in your code. I'll try to redirect all api.telegram.org  queries  via some vpn
