### ISSUE TITLE
Telegram with MMM-Youtube is not working

### ISSUE THREAD

**Issue by renzo79** [MMRIZE/MMM-TelegramBot#36]
Hello,

I´ve installed Telegram and Youtube but in combination Telegram is not working. It is only working when I remove the module MMM-Youtube in the config. I´ve started only these two modules in a simple config and I am getting followin Error-Message when I am sending a Telegram command to the mirror.
What can I do?
![image](https://user-images.githubusercontent.com/60211833/78745363-3ae50700-7964-11ea-8be1-b4bdc70223f4.png)

Thousands thanks

Again ;-)

**Comment by eouia** [comment]
I think you probably have something wrong about commands config of MMM-Youtube. try to remove `telegramBotCommand: ` part in your config.
