### ISSUE TITLE
Can’t get my chat id

### ISSUE THREAD

**Issue by sdmydbr** [MMRIZE/MMM-TelegramBot#38]
Hi, so I am running magic mirror on raspberry pi 4 and telegram app on iPhone 7 with iOS 13. 
I have installed the telegram bot as per the instructions and I can get upto the api but when I add the api to my config and restart the mirror, i try to get the chat Id in telegram but I can’t succeed, it says unrecognised command, say what?..
What am I doing wrong

**Comment by thymon13** [comment]
You need to launch a conversation with your news bot created. Not with BotFather.

**Comment by bugsounet** [comment]
@thymon13 you have right,
I have tested with a fresh install

@sdmydbr say to BotFather ... so it don't work
To talk to your bot:
above the token you have the link to talking to your bot !
like : `t.me/<your bot name>` just click on it :)

**Comment by sdmydbr** [comment]
Thank you.. it’s Solved now

**Comment by Beastlynoob** [comment]
Hello, I clicked on the link that BotFather gave me to allow me to chat with the new bot that was created but when I clicked start and tried talking to my bot nothing happened It didn't even allow me to do /help
