### ISSUE TITLE
Telecast Errors

### ISSUE THREAD

**Issue by semyag** [MMRIZE/MMM-TelegramBot#39]
Hello all! Currently im getting an error message in the DEV Console when trying to telecast and the messages are not popping up. 
![image](https://user-images.githubusercontent.com/65565430/82472125-ab1f9600-9a95-11ea-98e6-87bd82e24e6a.png)

I tested out a few commands, sent out notifications, took a screenshot. Made sure privacy mode was off for the bot however only thing that seems to fail is the telecast. Attaching config in case its something I missed API keys and names replaced. 

{
  module: 'MMM-TelegramBot',
  config: {
	position: "center",
    telegramAPIKey : '********',
    allowedUser : ['*****'],
    adminChatId : '*********',
   allowedUser: ["******"],
    useWelcomeMessage: true,
 
    
    telecast: "*******", // true or chat_id
    telecastLife: 60,
    telecastLimit: 5,
    telecastHideOverflow: false,
    
commandAllowed: {
  "telecast": ["******"],
  "mychatid": ["******"],
  "modules": ["*****"],
}
  }
},

**Comment by bugsounet** [comment]
> telecastLife: 60,

means 60ms and chat will be disappeared
but ... do you want really 60ms !?

**Comment by semyag** [comment]
Okay, you got me there, SO I upped it to 10000MS just to make sure that wasnt it. Still getting that error message only happens when I send a telecast.  Also uppded the telecastlimit to 500.

**Comment by bugsounet** [comment]
i will inspect

**Comment by semyag** [comment]
Thanks! 
If you need more details or anything let me know.

**Comment by bugsounet** [comment]
hi, inspected, there is some bug but not related to your issue

I think it's just because, you dont set the position of the module

sample
```
    {
      module: "MMM-TelegramBot",
      position: 'top_center',
      config: {
        telegramAPIKey : "xxx",
        allowedUser : ["bugsounet"], // This is NOT the username of bot.
        adminChatId : xxx,
        telecast: xxx,
        useWelcomeMessage: false,
        verbose: false,
      }
    },
```

and in your config:
you have set the position of the module inside the config {}

```
{
   module: 'MMM-TelegramBot',
   config: {
     position: "center",
     ...
   }
},
```
