### ISSUE TITLE
/alert is sent 6 times

### ISSUE THREAD

**Issue by 3DJupp** [MMRIZE/MMM-TelegramBot#4]
when i send /alert test i will get 6 reponses from the bot.

**Comment by eouia** [comment]
Thanks for reporting. I'll check

**Comment by eouia** [comment]
@Dom1n1c I cannot find any suspicious. Only /alert responded 6 times? Or other commands also?

**Comment by eouia** [comment]
@Dom1n1c have you still this problem? Do you need something to help more?

**Comment by 3DJupp** [comment]
Seems to be a bit tricky with this kind of error. I would expect one confirmation instead of 3 or 6 replies. 

I can not reproduce it right now, but it is a great module so far :)
