### ISSUE TITLE
telecast messages Emojis not displayed correctly

### ISSUE THREAD

**Issue by CyberRagz** [MMRIZE/MMM-TelegramBot#41]
The module is working perfectly in all aspects. However, when i send a /telecast message with Emojis from the bot the Emojis are displayed as simple outline images (Screenshot attached) . Also the profile picture of sender is not displayed on the screen instead the first letter of the name is displayed even though the sender has set a profile picture. Is there any configuration i have missed or need to do? 

![bot](https://user-images.githubusercontent.com/5304451/82815271-79a03380-9eb6-11ea-9ed5-eadf92292c55.jpg)

**Comment by eouia** [comment]
emoji is dependent on the system and emoji-font. For example, smile emoji on iPhone and Andriod are different.

For the picture.. hmmm.. not able to say anything without log. Check your `cache` folder.

**Comment by CyberRagz** [comment]
Well I am sending telecast messages from an Android phone. OP6T with latest OS. Of course the Emojis display okay on the phone chat message.  The Cache folder is empty no Log. 'Verbose' is set to 'true'.

**Comment by eouia** [comment]
emoji is just Unicode set not image itself and how it has to be displayed is dependent on the client.

https://unicode.org/emoji/charts/full-emoji-list.html
As you see above links, Each environment has different emoji icon for the same code. 
And for the Chromium of Raspbian, there is no color emoji font in the system by default. (as far as I know)
You need to import MS's Segeo or Google's Noto to get full color emoji fonts.


Try this. (I didn't test so not guarantee)
```sh
cd ~
mkdir ~/tmp
cd tmp
wget https://fontsdata.com/zipdown-segoeuiemoji-132714.htm 
wget https://noto-website.storage.googleapis.com/pkgs/NotoColorEmoji-unhinted.zip
mv zipdown-segoeuiemoji-132714.htm segoeuiemoji.zip
unzip segoeuiemoji.zip
unzip NotoColorEmoji-unhinted.zip
mkdir /home/pi/.fonts &>/dev/null
mv seguiemj.ttf "/home/pi/.fonts/Segoe UI.ttf"
mv NotoColorEmoji.ttf "/home/pi/.fonts/Noto Color Emoji.ttf"
fc-cache -f -v &>/dev/null
rm -r ~/tmp
```

**Comment by CyberRagz** [comment]
Thanks for the help. I did as suggested and got it working. The Emojis are being displayed now.
![emoji](https://user-images.githubusercontent.com/5304451/83022384-14c91280-a049-11ea-8f37-71e66623177c.jpg)
So one issue solved. Thanks. However, the sender profile picture is not displaying as can be seen from the attached screenshot. Any solution for this?
Thanks for all your help.

**Comment by eouia** [comment]
Hmmm if your profile "HAVE" a profile picture, image should be displayed.

Test this;
- Open 2 terminal shells(Or file manager). One for running MM, one for observing your directories.
- Run MM on one terminal.
- Send some messages from Telegram
- When the chat is appeared, do not turn off MM, Just move a focus to your second terminal (Alt + Tab or Ctrl + Tab will work)  See the directory `/cache` of this module. 
```sh
cd ~/MagicMirror/modules/MMM-TelegramBot/cache
ls -al
```
It will show some files(with a long name). One of them probably is your profile icon.

But if not there... Hmmm. I don't know why at this moment.

**Comment by idem2lyon** [comment]
Hello, 
I have my Profile picture, no problem, but I can't see my emoji (I do the trick but still unicolor emoji) and my stickers sent.
![image](https://user-images.githubusercontent.com/1819209/83903150-ed1b2e00-a75d-11ea-8f39-5614bac390da.png)

Other issue, if I send 2 or 3 pictures, position of my whole magicmirror change...
![image](https://user-images.githubusercontent.com/1819209/83903198-fefcd100-a75d-11ea-988f-33613bf3d0ff.png)

Do you have the same?

**Comment by bugsounet** [comment]
I will try to add it in installer with special npm command ;)

**Comment by bugsounet** [comment]
coded with the latest version ;)

**Comment by CyberRagz** [comment]
Thanks for the update. It works
