### ISSUE TITLE
Telegrambot error :- "You are not allowed to command me, ask admin"

### ISSUE THREAD

**Issue by clify007** [MMRIZE/MMM-TelegramBot#43]
Hi,

Thank you for this wonderful module, which comes in so handy.

I have been using MMM-Telegrambot previously without any problems. Unfortunately my sd card was corrupted and I had to reinstall everything on a new SD card.

Problem is now my bot is not reacting and keeps throwing the error message whenever I  try /start.
No other command seem to work. 
I have created a new bot as well still no luck.

My config sample:- 
{
	module: 'MMM-TelegramBot',
	config: {
    		telegramAPIKey : 'myapi',
    		allowedUser : ["Mmbot"],
    		//adminChatId : ‘Cannot get this as bot is not reacting’,
  		},
},
Could you please help, as to what may be the problem. I have spent more than 3 hours last night trying all possibilities.

Using my old setup does not work as I deleted the bot in my app. Now im stuck.

**Comment by bugsounet** [comment]
sometime... reading Readme help no ?

in this [part](https://github.com/bugsounet/MMM-TelegramBot#3-configuration-pre-use)
