### ISSUE TITLE
Messages are displayed twice

### ISSUE THREAD

**Issue by Sebastian-Voigt** [MMRIZE/MMM-TelegramBot#45]
Hi,

I am now shown all the messages twice. even if I write the bot with / Commands, I get an answer twice.

Can someone tell me what I can do?

the config looks like this:

{
			"module": "MMM-TelegramBot",
			"position": "top_right",
			"config": {
				"telegramAPIKey": "*********************************************",
				"allowedUser": [
					"name1",
					"name2",
					"name3"
				],
				"adminChatId": *************,
				"favourites": [
					"/commands",
					"/modules",
					"/hideall",
					"/showall"
				],
				"screenshotScript": "scrot",
				"useWelcomeMessage": false,
				"detailOption": {},
				"telecast": *************,
				"telecastLife": ************,
				"telecastLimit": 5,
				"telecastHideOverflow": true
			}
		},

Sorry for my english, it's translate with googel. :-)

**Comment by bugsounet** [comment]
corrected with latest version [TelegramBot Service] check this
