### ISSUE TITLE
Stickers and GIFs not displayed while telecasting

### ISSUE THREAD

**Issue by phasec** [MMRIZE/MMM-TelegramBot#48]
When using the permanent telecasting with the chat id, only text messages and pictures are displayed on the Magic Mirror. GIFs, Stickers and Locations are just ignored. Is this intentional?

**Comment by bugsounet** [comment]
I take own this module, and not really inspect it

I see some bug to solve and i will see what's coded really.
Other module take me many time.
but Now I can inspect it ;)

**Comment by bugsounet** [comment]
![photo_2020-09-05_17-28-54](https://user-images.githubusercontent.com/30669209/92308375-67499180-ef9d-11ea-9541-b0ed7bfed466.jpg)

in progress !

Actually added:
 * Official notification sound on incoming message
 * stickers support (but not animated)

Gifs is more complex ... Telegram return an MP4 link :(

Planned too : 
 * read audio file received
 * read video file received

nothing is lost yet .. i'm coding :)

**Comment by bugsounet** [comment]
done with v1.3.3 :) 

Gifs / notification sound /  stickers
