### ISSUE TITLE
useWelcomeMessage does not disable the welcome message

### ISSUE THREAD

**Issue by Unbekannt1998** [MMRIZE/MMM-TelegramBot#59]
Hi,
 after the latest update or one in the last 12 commits cant tell exactly. But after my update the bot sends me the welcome Message even if useWelcomeMessage is set to false. My config:
```
{
      module: 'MMM-TelegramBot',
      config: {
        telegramAPIKey: 'XXX',
        allowedUser: [
          'XXX'
        ],
        adminChatId: XXX,
        useWelcomeMessage: false,
        commandAllowed: {},
        detailOption: {},
        favourites: [
          '/commands',
          '/modules',
          '/hideall',
          '/showall'
        ],
        customCommands: []
      }
    }
```

Kind regards

**Comment by bugsounet** [comment]
can't happen ... but maybe ...
In all case, with @latest version i don't use MM default merging config, i use another since today.

But ... Maybe to you have an  `Mini-Welcome` (without date of restarting)
In this case TelegramBot have detected an Fatal Error (network failed, 401 UNAUTHORIZED, ...)
So I Try to reconnect with sending `mini-Welcome` message for control (If it's that, i will try to do better)

I Try to solve all MMM-TelegramBot bug (many bug... and flooding error... and take many many place in MM log ... -> preserv in good condition)

**Comment by Unbekannt1998** [comment]
thanks for the fast replay
it probably is the mini-welcome but i see no errors in my log 
![Screenshot from 2020-09-11 09-27-06](https://user-images.githubusercontent.com/20846147/92883324-085aa100-f411-11ea-8082-b118ec412cd0.png) 
(the messages translate roughly to 
```
I have awaken from deep sleep.

 Service provided by TelegramBot service
```
)

**Comment by bugsounet** [comment]
under coding ...
I will do better :)

**Comment by bugsounet** [comment]
fixed with the last release

**Comment by Unbekannt1998** [comment]
thank you 
my last message was not a intended to make you stress and rush things it was just intended to give you more info
to fix the error
and again thank for the fast fix will test rn and will send feedback

**Comment by bugsounet** [comment]
don't worry about this ! I'm not stressed !

Now with the last update, it will show the error find... in your case i think maybe internet missing

you can disable alert in config :)

I try to do the maximum with TelegramBot

again, telecast is now complete ;)
TelegramBot can now read photo, video, audio, stickers, ...

See Readme and adjust your conf :)

Thx for your feedback
@bugsounet

**Comment by Unbekannt1998** [comment]
so after like a day i can say the last version fixed the issue and i don't get spammed with messages anymore thanks again for the quick fix. 
I use the bot mostly to administrate my mirror so i will probably not use the other option because my mirror is already  cluttert with other stuff, so i will not use the other options even so I like the possibility for them.
