### ISSUE TITLE
MMM-TelegramBot & updatenotification

### ISSUE THREAD

**Issue by johnlucajf** [MMRIZE/MMM-TelegramBot#66]
Hi @bugsounet ,

I've got an issue when updatenotifcation restarts after applying update.

What happens is:

Mirror is automatically started with pm2, updatenotification detects update and restarts mirror. Then i get several messages from Telegram saying 
"[Warning] Make sure that only one TelegramBot instance is running"

then a final one saying
"[Warning] This instance of TelegramBot is now stopped!"

After this Telegram is still working as i can broadcast to mirror, and commands still work, but i dont get any feedback , so if i type in \commands or \status,  no repsonse but if type \reboot that does work. 
and once rebooted everytthing is working correctly.

Thanks
John

**Comment by bugsounet** [comment]
Hi, MagicMirror is running 2 times

just verify your [UN] configuration (verify using pm2 and verify pm2 name)
in all case, It's not an issue for [TB]
