### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by bk24z** [MMRIZE/MMM-TelegramBot#67]
Every time I start MagicMirror, I get spammed with these two notifications and then the bot stops working.

![image](https://user-images.githubusercontent.com/58478977/103152642-ec8dc780-4781-11eb-8d1d-9113d92fa335.jpeg)

**Comment by bugsounet** [comment]
You have 2 instance of MagicMirror running... So you have 2 bot running

So Telegram Api refuse it

Can happen when you use module like Remote Control (Bad coding module) for example

**Comment by bk24z** [comment]
Disabling the remote control module fixed it. Thank you, @bugsounet !

**Comment by bugsounet** [comment]
Note: I will recode entirely MMM-remote-control module. Because it very badly coded... Like a newbie...

**Comment by bk24z** [comment]
Yeah that would be helpful as the remote control module does some things that the telegram bot can't 😁

**Comment by bugsounet** [comment]
😂 If you says that... Humm it's so funny. I think it s better for you using remote control, you don't know the power telegrambot Api ;)
