### ISSUE TITLE
service stop - integration remote control module

### ISSUE THREAD

**Issue by chen32g** [MMRIZE/MMM-TelegramBot#71]
Hello,

When I open the Magic Mirror also via Remote Control module on website I got the message on Telegram Bot:
[WARNING] Make sure that only one TelegramBot instance is running!
Served by TelegramBot Service
[WARNING] This instance of TelegramBot is now stoped!
Served by TelegramBot Service

Of course it's happen because the MagicMirror run twice in the same time but my problem is after the service is stop and I close the Magic Mirror Remote Control module via web how can I restart the TelegramBot Service and turn it back on?

Thank you.

**Comment by bugsounet** [comment]
I will try to code a Retry part. But I have to see if the client part code is deleted or not when exit remote control display

I never close the socket... Telegrambot will will never run

In all case I will do some test
